### GET request to example server
POST http://localhost:8080/auth/login
Content-Type: application/json

{   "username": "najdovski", "password": "admin123" }


###

POST http://localhost:8080/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoibmFqZG92c2tpIiwiaWF0IjoxNzU1ODEwNzY3LCJleHAiOjE3NTU4MTQzNjd9.rPl4ik7S1Akph2Lop4tAWl5qtobT_KTlBrGvAdVMXRA
Content-Type: application/json

{
  "name": "Kitchen Renovation",
  "description": "Full kitchen rebuild with new cabinets and appliances"
}


###