### GET request to example server
POST http://localhost:8080/auth/login
Content-Type: application/json

{   "username": "najdovski", "password": "admin123" }


###

### Get all materials (authorized)
GET http://localhost:8080/api/materials
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoibmFqZG92c2tpIiwiaWF0IjoxNzU2MzA0MzIxLCJleHAiOjE3NTYzMDc5MjF9.p-NrU_Pys3qYiOKHvMB-93Cup_YbmCXfg2o3actAAo8

Accept: application/json


###